/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TicTacToe;

import TicTacToe.Controller.MainController;

/**
 * Main class of the application
 */
public class App {

    /**
     * Main method of the application
     * @param args command line arguments (currently none required)
     */
    public static void main(String[] args) {
        new MainController();
    }
}
