/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TicTacToe;

import TicTacToe.Controller.MainController;

public class App {

    public static void main(String[] args) {
        new MainController();
    }
}
